export const INITROOMINFO = 'INITROOMINFO'
export const UPDATEROOMINFO = 'UPDATEROOMINFO'

export const INITPRODUCTDATA = 'INITPRODUCTDATA'
export const UPDATEPRODUCTDATA = 'UPDATEPRODUCTDATA'

export const INITUSERINFO = 'INITUSERINFO'
export const UPDATEUSERINFO = 'UPDATEUSERINFO'

export const INITTIMER = 'INITTIMER'
export const CLEARCHATINFO = 'CLEARCHATINFO'
export const UPDATECHATINFO = 'UPDATECHATINFO'
export const UPDATEPRODUCTTIMER = 'UPDATEPRODUCTTIMER'
export const CLEARPRODUCTINFO = 'CLEARPRODUCTINFO'

