export const INITROOMINFO = 'INITROOMINFO'
export const UPDATEROOMINFO = 'UPDATEROOMINFO'

export const INITPRODUCTDATA = 'INITPRODUCTDATA'
export const UPDATEPRODUCTDATA = 'UPDATEPRODUCTDATA'

export const INITUSERINFO = 'INITUSERINFO'
export const UPDATEUSERINFO = 'UPDATEUSERINFO'
